### ISSUE TITLE
The pointer you are trying to remove does not exist in the mapping dict!

### ISSUE THREAD

**Issue by shoukailiang** [mertusta1996/Drawer-Hololens2-Unity#1]
![image](https://user-images.githubusercontent.com/24668909/219867263-644db5f2-3517-4797-a827-7c92681de81b.png)
What is the issue with these error messages

**Comment by mertusta1996** [comment]
Hi @shoukailiang  ,

First, this log error has no effect on our operation. MRTK just adds a log error when it loses hand detection in the scene.

This logerror's reason is my main script using "IMixedRealityPointerHandler". And this interface's main operative c# script is "MixedRealityInputModule.cs". So we are using this script too.
In this script; when hand detection lost in scene, says our pointers removed and we could try to reach maybe. 
But in my script, I didn't use any function when hand detection lost. So it would not has any effect for our scripts. MRTK just adds a logerror in this line("The pointer you are trying to remove does not exist in the mapping dict!"), but not any effect for the operation. So, we can ignore it.
 
Source: line 433 in "MixedRealityInputModule.cs"
![issue1_ss](https://user-images.githubusercontent.com/70747383/220206986-c8ca4f97-80dc-454f-9e0b-5729a2882d36.PNG)

Thanks for your response :)

**Comment by shoukailiang** [comment]
Thank you for your reply.
