### ISSUE TITLE
why the scripts can launch automaticly?

### ISSUE THREAD

**Issue by joyfulmerry** [mertusta1996/Drawer-Hololens2-Unity#3]
Excuse me, I have a problem about the launch of scripts.  I just learned the unity and hololens2 for a few days, a rookie.  But I don't even know how your scripts awake with no mounting.  As far as I learned, the script need being mounted to some object as component then It can work.  After some searching and code understanding, I think I need help from you.  Thank you for reading this!

**Comment by mertusta1996** [comment]
Hello @joyfulmerry ,
For this project I checked my scene hierarchy. I'm managing 2 main systems.

First main system, I have "DrawerScript" gameObject, this gameObject's location is "MixedRealityPlayspace/Main Camera/DrawerScript" and this gameObject has "DrawerScript.cs" code. This code is handling all drawing actions. (This script is inheriting "IMixedRealityPointerHandler" interface, this interface has some Hand Pointer actions, this actions giving a capability to work my "AddDrawing" method when hand pointers state is "OnPointerDown" and this state is "selecting with hand" state in Hololens2 device.)

Second main system, I have "HandMenuSliderController" gameObject, this gameObject's location is "HandMenu/Hand Menu Slider Controller"  and this gameObject has "DrawerHandMenuSliderController.cs" code. This code is managing some sliders (some slider's SliderEvent's referencing this script).

And lastly, some slider gameObject's has "DrawerHandMenuSlider.cs" script, this script manages slider's own capabilities.
Enjoy your work, happy coding 👍

**Comment by joyfulmerry** [comment]
Thank you so much, mert usta! After the question mail, I did more unity learning and I finally figured it out. As you said, the scripts work in the scence, I just made a low-level mistake.&nbsp;


Your detailed explanation is so helpful for my unity learning and your reply means a lot to me，you are so generous and welcoming，thank you and hope you have a good life！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mertusta1996/Drawer-Hololens2-Unity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月18日(星期一) 下午3:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mertusta1996/Drawer-Hololens2-Unity] why the scripts can launch automaticly? (Issue #3)





 
Hello @joyfulmerry ,
 For this project I checked my scene hierarchy. I'm managing 2 main systems.
 
First main system, I have "DrawerScript" gameObject, this gameObject's location is "MixedRealityPlayspace/Main Camera/DrawerScript" and this gameObject has "DrawerScript.cs" code. This code is handling all drawing actions. (This script is inheriting "IMixedRealityPointerHandler" interface, this interface has some Hand Pointer actions, this actions giving a capability to work my "AddDrawing" method when hand pointers state is "OnPointerDown" and this state is "selecting with hand" state in Hololens-2 device.)
 
Second main system, I have "HandMenuSliderController" gameObject, this gameObject's location is "HandMenu/Hand Menu Slider Controller"  and this gameObject has "DrawerHandMenuSliderController.cs" code. This code is managing some sliders (some slider's SliderEvent's referencing this script).
 
And lastly, some slider gameObject's has "DrawerHandMenuSlider.cs" script, this script manages slider's own capabilities.
 Enjoy your work, happy coding 👍

**Comment by MansNilsson-hub** [comment]
Hi @mertusta1996 
I had a question regarding adding eventual new functions to the application

I wanted to try this application out for myself and it has worked very well with some projects I've been working on. But I wanted to know how or what you could do to implement new features? I'm a total beginner in all kinds of programming, so I've been using AI and YouTube tutorials to help me learn. I want to add an "Undo Last Drawing", a "Clear All" and a "QuitApplication" feature that I've want to be accessible from the hand menu. I've altered the DrawerScript to allow you to make these changes and I've created the buttons necessary and I've added the script to these individual buttons, but when I've tried to boot up the application in the HoloLens, the buttons seemingly are not interactable and don't perform the function I want them to.

If you have any ideas or tips on how I could fix this, it would be greatly appreciated. Thank you in advance
